---
title: "PLACE_to_Cousub_Crosswalk_for_PSH"
author: "Will Payne"
date: "5/123/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
########################################
## 1 - Setup and Initializing Dataset ##
########################################

library(sf) # use this to read geojsons and shapefiles
library(htmltools)
library(tmap) # use this to map them
library(dplyr) # use this to join and manipulate data frames
library(tidyverse)
library(readxl) # use this to read excel files

place_PSH_2023_ALL <- read.csv(file = 'PLACE_2023.csv') # read in national place-level data
tract_PSH_2023_AK_MN <- read_excel("TRACT_AK_MN_2023_2020census.xlsx") # same for tracts part 1
tract_PSH_2023_MO_WY <- read_excel("TRACT_MO_WY_2023_2020census.xlsx") # same for tracts part 2

state_name <- 'NJ New Jersey' # set this once and everything flows from here
cousub_year <- '2023' # set this one and everything flows from here
state_abbreviation <- substring(state_name,1,2) # set this once and everything flows from here

place_PSH_2023 <- place_PSH_2023_ALL %>% filter(grepl(state_name, states)) # filter to single state
state_code <- substr(head(place_PSH_2023,1)$code,1,2) # store state code

place_PSH_2023 <- subset(place_PSH_2023, select = -c(gsl,states,sumlevel,sub_program,entities, fedhse, cbsa, latitude, longitude, state, pha_total_units, ha_size)) # remove unneeded columns
place_PSH_2023[place_PSH_2023==-1]<-0 # replace -1 with 0 throughout (missing data)
place_PSH_2023[place_PSH_2023==-4]<-NA # replace -4 with NA throughout (suppressed demographic data)
place_PSH_2023[place_PSH_2023==-5]<-NA # replace -5 with NA throughout (reporting under 50% demographic data)

state_list_tracts_1 <- unique(tract_PSH_2023_AK_MN$states) # list of states in the first tract file

if (state_name %in% state_list_tracts_1) {
  tract_PSH_2023 <- tract_PSH_2023_AK_MN %>% filter(grepl(state_name, states)) # use first tract file
} else {
  tract_PSH_2023 <- tract_PSH_2023_MO_WY %>% filter(grepl(state_name, states)) # use second tract file
}

tract_PSH_2023 <- subset(tract_PSH_2023, select = -c(gsl,states,sumlevel,sub_program,entities, fedhse, cbsa, latitude, longitude, state, pha_total_units, ha_size)) # remove unneeded columns
tract_PSH_2023[tract_PSH_2023==-1]<-0 # replace -1 with 0 throughout (missing data)
tract_PSH_2023[tract_PSH_2023==-4]<-NA # replace -4 with NA throughout (suppressed demographic data)
tract_PSH_2023[tract_PSH_2023==-5]<-NA # replace -5 with NA throughout (reporting under 50% demographic data)

rm(place_PSH_2023_ALL, tract_PSH_2023_AK_MN, tract_PSH_2023_MO_WY, state_list_tracts_1) # remove big files outputs

##########################################
## 2 - Combining Data from All Programs ##
##########################################

# do this for place-level data first
prefixes <- unique(place_PSH_2023$program) # get all the unique program names used in the dataset

place_PSH_2023 <- pivot_wider( # pivot them to one row per cdp/cousub/remainder
  place_PSH_2023,
  id_cols = NULL,
  names_from = program,
  names_prefix = "",
  names_sep = "_",
  names_glue = "Pg{program}_{.value}",
  values_from = c(program_label,total_units,pct_occupied,number_reported,pct_reported,months_since_report,months_since_report,pct_movein,people_per_unit,people_total,rent_per_month,spending_per_month,hh_income,person_income,pct_lt5k,pct_5k_lt10k,pct_10k_lt15k,pct_15k_lt20k,pct_ge20k,pct_wage_major,pct_welfare_major,pct_other_major,pct_median,pct_lt50_median,pct_lt30_median,pct_2adults,pct_1adult,pct_female_head,pct_female_head_child,pct_disabled_lt62,pct_disabled_ge62,pct_disabled_all,pct_lt24_head,pct_age25_50,pct_age51_61,pct_age62plus,pct_age85plus,pct_minority,pct_black_nonhsp,pct_native_american_nonhsp,pct_asian_pacific_nonhsp,pct_white_nothsp,pct_black_hsp,pct_wht_hsp,pct_oth_hsp,pct_hispanic,pct_multi,months_waiting,months_from_movein,pct_utility_allow,ave_util_allow,pct_bed1,pct_bed2,pct_bed3,pct_overhoused,tpoverty,tminority,tpct_ownsfd),
  names_sort = TRUE
)

# sort the dataframe so that each set of unit counts and demographic variables are together by program
names_to_order <- map(prefixes, ~ names(place_PSH_2023)[grep(paste0(.x,"_"), names(place_PSH_2023))]) %>% unlist
names_id <- setdiff(names(place_PSH_2023), names_to_order)
place_PSH_2023 <- place_PSH_2023 %>%
  select(all_of(names_id), names_to_order)

# and then for tract-level data
prefixes <- unique(tract_PSH_2023$program) # get all the unique program names used in the dataset

tract_PSH_2023 <- pivot_wider( # pivot them to one row per cdp/cousub/remainder
  tract_PSH_2023,
  id_cols = NULL,
  names_from = program,
  names_prefix = "",
  names_sep = "_",
  names_glue = "Pg{program}_{.value}",
  values_from = c(program_label,total_units,pct_occupied,number_reported,pct_reported,months_since_report,months_since_report,pct_movein,people_per_unit,people_total,rent_per_month,spending_per_month,hh_income,person_income,pct_lt5k,pct_5k_lt10k,pct_10k_lt15k,pct_15k_lt20k,pct_ge20k,pct_wage_major,pct_welfare_major,pct_other_major,pct_median,pct_lt50_median,pct_lt30_median,pct_2adults,pct_1adult,pct_female_head,pct_female_head_child,pct_disabled_lt62,pct_disabled_ge62,pct_disabled_all,pct_lt24_head,pct_age25_50,pct_age51_61,pct_age62plus,pct_age85plus,pct_minority,pct_black_nonhsp,pct_native_american_nonhsp,pct_asian_pacific_nonhsp,pct_white_nothsp,pct_black_hsp,pct_wht_hsp,pct_oth_hsp,pct_hispanic,pct_multi,months_waiting,months_from_movein,pct_utility_allow,ave_util_allow,pct_bed1,pct_bed2,pct_bed3,pct_overhoused,tpoverty,tminority,tpct_ownsfd),
  names_sort = TRUE
)

# sort the dataframe so that each set of unit counts and demographic variables are together by program
names_to_order <- map(prefixes, ~ names(tract_PSH_2023)[grep(paste0(.x,"_"), names(tract_PSH_2023))]) %>% unlist
names_id <- setdiff(names(tract_PSH_2023), names_to_order)
tract_PSH_2023 <- tract_PSH_2023 %>%
  select(all_of(names_id), names_to_order)

rm(names_id, names_to_order) # remove intermediate outputs

###########################################
## 3 - Split Place Dataset by Error Type ##
###########################################

code_99999 <- paste(state_code, '99999', sep='') # state geoid for unjoinable geographies
code_XXXXX <- paste(state_code, 'XXXXX', sep='') # state geoid for units lacking location information

# find out what to do with CDPs, which in CT and NY also include other non-governmental place types
if (state_code == '09'){
    place_PSH_CDPs <- place_PSH_2023 %>% filter(grepl('CDP|BOROUGH', name)) # extract CDPs
    print("I'm in Connecticut!")
  } else {
    if (state_code == '36'){
      place_PSH_CDPs <- place_PSH_2023 %>% filter(grepl('CDP|VILLAGE', name)) # extract CDPs
      print("I'm in New York!")
      } else {
        place_PSH_CDPs <- place_PSH_2023 %>% filter(grepl('CDP', name)) # extract CDPs
      }
  }
place_PSH_no_CDPs <- place_PSH_2023 %>% filter(!grepl('CDP', name)) # remove CDPs from the main dataset

# divide others into rows with geoids and ones without them
place_PSH_999999s <- filter(place_PSH_no_CDPs, code == code_99999) # extract rows without geoids, including remainders
place_PSH_geoID <- filter(place_PSH_no_CDPs, code != code_99999) # extract non-CDPs with working geoids

# separate missing values
place_PSH_bad_XXXXX <- filter(place_PSH_no_CDPs, code == code_XXXXX) # extract missing values (unmappable)
place_PSH_geoID <- filter(place_PSH_geoID, code != code_XXXXX) # remove missing values (unmappable)

# solve an issues where HUD is using 2020 CDP geometries but only has 2010 names
# basically some CDPs show up with the correct geoid but are called "(remainder of)/X township" mistakenly
place_PSH_geoID_CDPs <- place_PSH_geoID %>% filter(grepl('TOWNSHIP', name)) # extract non-remainders (CDPs) with working geoids from the geoid section
place_PSH_CDPs <- rbind(place_PSH_CDPs, place_PSH_geoID_CDPs) # bind those together with CDPs
place_PSH_geoID_noCDPs <- place_PSH_geoID %>% filter(!grepl('TOWNSHIP', name)) # save the rest of them

# divide 999999s between remainders and regular county subdivisions
place_PSH_remainders <- place_PSH_999999s %>% filter(grepl('REMAINDER', name)) # extract remainders of cousubs
place_PSH_othercousubs <- place_PSH_999999s %>% filter(!grepl('REMAINDER', name)) # extract other cousubs without geoids

rm(place_PSH_999999s,place_PSH_geoID,place_PSH_geoID_CDPs,place_PSH_no_CDPs) # remove intermediate outputs

#######################################
## 4 - Find Unjoinable Units by Type ##
#######################################

# We do this before anything else in order to have a sense of the scope of the problem

unjoinable_units_by_type <- data.frame(matrix(ncol = 7, nrow = 9)) # initialize empty dataframe
colnames(unjoinable_units_by_type) <- c("Pg","Name", "Total_units", "unjoin_Missing","unjoin_CDP", "unjoin_Remainder","unjoin_99999")
unjoinable_units_by_type$Pg <- 1:9 # initialize with all possible program numbers
unjoinable_units_by_type$Name <- c("All Programs", "Public Housing", "Housing Choice Vouchers", "Moderate Rehabilitation", "Project Based Section 8", "RentSup/RAP", "S236/BMIR", "202/PRAC", "811/PRAC") # and names
  
for(i in 1:length(prefixes)) { # loop to get unjoinable units by type of error and program number
  totalname <- paste('Pg', as.character(prefixes[i]), '_total_units', sep = "")

  unjoinable_99999_column <- place_PSH_othercousubs[grepl(totalname,colnames(place_PSH_othercousubs))]
  unjoinable_units_by_type[unjoinable_units_by_type$Pg==prefixes[i], "unjoin_99999"] <- sum(unjoinable_99999_column,na.rm=TRUE)

  unjoinable_CDP_column <- place_PSH_CDPs[grepl(totalname,colnames(place_PSH_CDPs))]
  unjoinable_units_by_type[unjoinable_units_by_type$Pg==prefixes[i], "unjoin_CDP"] <- sum(unjoinable_CDP_column,na.rm=TRUE)

  unjoinable_remainder_column <- place_PSH_remainders[grepl(totalname,colnames(place_PSH_remainders))]
  unjoinable_units_by_type[unjoinable_units_by_type$Pg==prefixes[i], "unjoin_Remainder"] <- sum(unjoinable_remainder_column,na.rm=TRUE)

  missing_column <- place_PSH_bad_XXXXX[grepl(totalname,colnames(place_PSH_bad_XXXXX))]
  unjoinable_units_by_type[unjoinable_units_by_type$Pg==prefixes[i], "unjoin_Missing"] <- sum(missing_column,na.rm=TRUE)

  total_summary_column <- place_PSH_2023[grepl(totalname,colnames(place_PSH_2023))]
  unjoinable_units_by_type[unjoinable_units_by_type$Pg==prefixes[i], "Total_units"] <- sum(total_summary_column,na.rm=TRUE)
  
  rm(i, totalname, unjoinable_99999_column, unjoinable_CDP_column, unjoinable_remainder_column, missing_column, total_summary_column) 
}

unjoinable_units_by_type$total_joinable <- unjoinable_units_by_type$Total_units - unjoinable_units_by_type$unjoin_Missing
unjoinable_units_by_type$unjoin_CDP_Pct <- unjoinable_units_by_type$unjoin_CDP/unjoinable_units_by_type$total_joinable *100
unjoinable_units_by_type$unjoin_Remainder_Pct <- unjoinable_units_by_type$unjoin_Remainder/unjoinable_units_by_type$total_joinable *100
unjoinable_units_by_type$unjoin_99999_Pct <- unjoinable_units_by_type$unjoin_99999/unjoinable_units_by_type$total_joinable *100
unjoinable_units_by_type$total_unjoinable <- unjoinable_units_by_type$unjoin_CDP + unjoinable_units_by_type$unjoin_Remainder + unjoinable_units_by_type$unjoin_99999
unjoinable_units_by_type$total_unjoinable_Pct <- unjoinable_units_by_type$total_unjoinable/unjoinable_units_by_type$total_joinable *100

write.csv(unjoinable_units_by_type, paste0(state_abbreviation,"_unjoinable_units_by_type_2023.csv",sep=''), row.names=FALSE) # writes filename with state abbreviation, update later for different years

########################################
## 5 - Create CDP to Cousub Crosswalk ##
########################################

# read in Census places, subset to CDPs, remove fields, remove original dataset
Census_Place_2020 <- st_read(paste("Census_Geographies/2020_place/tl_2020_", state_code,"_place/tl_2020_", state_code, "_place.shp", sep = "")) # bring in Census Place level geometries
Census_CDPs_2020 <- Census_Place_2020 %>% filter(grepl('CDP', NAMELSAD)) #filter to only CDPs
Census_CDPs_2020 <- subset(Census_CDPs_2020, select = -c(PCICBSA, PCINECTA,STATEFP,INTPTLAT,INTPTLON,ALAND,AWATER,FUNCSTAT,LSAD,CLASSFP,MTFCC)) # remove extraneous fields
rm(Census_Place_2020)

# find the centroid of all CDPs in the state and get lon and lat
CDP_bounds <- st_bbox(Census_CDPs_2020) # get the bounding box for the CDPs in this state
CDP_centroid_lon <- (CDP_bounds[1] + CDP_bounds[3])/2 # average the longs
CDP_centroid_lat <- (CDP_bounds[2] + CDP_bounds[4])/2 # average the lats
rm(CDP_bounds)

# function below is adapted from code by Gordon McDonald from 8/10/2021, found here: https://gis.stackexchange.com/questions/13291/computing-utm-zone-from-lat-long-point

find_one_utm_zone <- function(longitude, latitude) { # function to find the right UTM zone
  if ( (latitude>-80.0) && (latitude<=84.0) ){
    mid_zones <- LETTERS[c(3:8,10:14,16:24)] # C to X, skip I and O
    utm_letter <- mid_zones[ min(floor( (latitude + 80) / 8 )+1 , 20) ]
    utm_number <- (floor( (longitude + 180) / 6 ) %% 60) + 1 # modulo in case longitude is 0 to 360 instead of -180 to 180
    utm_zone <- paste0(utm_number, utm_letter)
    return(utm_zone)
  } else {
      stop("lat long not valid (or something else broke)")
    }
}

# figure out the simple version of the UTM zone for this state
utm_zone <- find_one_utm_zone(CDP_centroid_lon, CDP_centroid_lat) # find the right UTM zone
utm_zone_simple <- substr(utm_zone, 1, nchar(utm_zone)-1)
rm(utm_zone, CDP_centroid_lat, CDP_centroid_lon)
rm(find_one_utm_zone)

# reproject the CDP layer to the correct UTM CRS, run a negative buffer, delete original dataset
CDP_2020_Proj <- st_transform(Census_CDPs_2020, paste0("+proj=utm +zone=",utm_zone_simple," +ellps=GRS80 +datum=NAD83", sep="")) #reproject to correct UTM zone
CDP_2020_Neg_Buffer <- CDP_2020_Proj %>% st_buffer(-150)  # create the negative 1000 foot buffer
CDP_2020_Neg_Buffer$sqkm <- as.numeric(st_area(CDP_2020_Neg_Buffer)/1000000) # add a square kilometer field
rm(Census_CDPs_2020, CDP_2020_Proj)

# bring in Census county subdivision geometries, subset, and reproject
Census_Cousubs <- st_read(paste("Census_Geographies/", cousub_year,"_cousub/tl_", cousub_year, "_", state_code,"_cousub/tl_",cousub_year,"_", state_code, "_cousub.shp", sep = "")) 
Census_Cousubs <- Census_Cousubs %>% filter(!grepl('not defined', NAME)) # extract non-remainders (CDPs) with working geoids
if (cousub_year == '2023') {
  Census_Cousubs <- subset(Census_Cousubs, select = -c(STATEFP,COUSUBNS,GEOIDFQ,INTPTLAT,INTPTLON,ALAND,AWATER,FUNCSTAT,LSAD,MTFCC)) # fields to drop
} else {
  Census_Cousubs <- subset(Census_Cousubs, select = -c(CNECTAFP,NECTAFP,NCTADVFP,STATEFP,INTPTLAT,INTPTLON,ALAND,AWATER,FUNCSTAT,LSAD,MTFCC))
 # different fields to drop
}

Cousubs_Proj <- Census_Cousubs %>% sf::st_transform(paste0("+proj=utm +zone=",utm_zone_simple," +ellps=GRS80 +datum=NAD83", sep="")) # reproject to UTM projection specified above
rm(Census_Cousubs)

# intersect CDPs and county subdivisions
CDP_Cousub_intersects <- st_intersection(CDP_2020_Neg_Buffer, Cousubs_Proj) # try this
CDP_Cousub_intersects$area <- as.numeric(st_area(CDP_Cousub_intersects)/1000000)
CDP_Cousub_intersects$coverage <- CDP_Cousub_intersects$area/CDP_Cousub_intersects$sqkm
CDP_Cousub_intersects <- st_drop_geometry(CDP_Cousub_intersects) # remove geometry

# subset to only CDPs that span munis
CDPs_with_Munis_Duplicates_Total <- duplicated(pull(CDP_Cousub_intersects,PLACEFP)) | duplicated(pull(CDP_Cousub_intersects,PLACEFP), fromLast=TRUE) # get duplicates and originals
CDPs_with_Munis_Duplicates_Total_List <- CDP_Cousub_intersects[CDPs_with_Munis_Duplicates_Total,c("NAMELSAD", "NAMELSAD.1","coverage","GEOID","GEOID.1")]
rm(CDPs_with_Munis_Duplicates_Total)
#write.csv(CDPs_with_Munis_Duplicates_Total_List,"duplicate_CDPs.csv")

# extract list of all muni GEOIDs that have ambiguous CDPs, and all CDPs to remove from automated process
Ambiguous_CDP_Muni_GEOID_List <- unique(CDPs_with_Munis_Duplicates_Total_List[['GEOID.1']])
Ambiguous_CDP_Muni_Name_List <- unique(CDPs_with_Munis_Duplicates_Total_List[['NAMELSAD.1']])
# these can have slightly different lengths, for example if two cousubs with the same name in different counties both contain CDPs that overlap other cousubs (Washington Township in NJ, for example)
CDPs_to_Remove <- unique(CDPs_with_Munis_Duplicates_Total_List[['GEOID']])
Cleaned_CDP_Cousub_Intersects <- CDP_Cousub_intersects %>% filter(! GEOID %in% CDPs_to_Remove)

place_PSH_bad_CDPs <- place_PSH_CDPs %>% filter(code %in% CDPs_to_Remove)
place_PSH_good_CDPs <- place_PSH_CDPs %>% filter(!code %in% CDPs_to_Remove)

rm(CDPs_with_Munis_Duplicates_Total_List, CDP_Cousub_intersects, place_PSH_CDPs)
rm(CDP_2020_Neg_Buffer)
rm(CDPs_to_Remove)

###################################
## 6 - Set Aside Handled Cousubs ##
###################################

place_PSH_Cousubs_Already <- rbind(place_PSH_geoID_noCDPs, place_PSH_othercousubs) # get things that are already aggregated to cousub put together here

place_PSH_Cousubs_Already$Join_Name <- str_to_title(substr(place_PSH_Cousubs_Already$name,4,nchar(place_PSH_Cousubs_Already$name))) # create new join field

rm(place_PSH_geoID_noCDPs, place_PSH_othercousubs) # remove intermediate steps

#######################################
## 7 - Aggregate CDPs and Remainders ##
#######################################

# join good CDPs with munis
place_PSH_good_CDPs_with_Munis <- left_join(place_PSH_good_CDPs, Cleaned_CDP_Cousub_Intersects, by = c("code" = "GEOID")) # put them together
rm(place_PSH_good_CDPs)

# find the list of repeated county subdivision names and GEOIDs
Ambiguous_Muni_Names_Boolean <- duplicated(pull(Cousubs_Proj,NAMELSAD)) | duplicated(pull(Cousubs_Proj,NAMELSAD), fromLast=TRUE)
Ambiguous_Muni_Names <- Cousubs_Proj[Ambiguous_Muni_Names_Boolean, c('COUNTYFP','NAMELSAD',"GEOID")]
Ambiguous_Muni_Names$PSH_Name <- paste(state_abbreviation,toupper(Ambiguous_Muni_Names$NAMELSAD))
Ambiguous_Muni_Name_List <- unique(Ambiguous_Muni_Names[['PSH_Name']])
Ambiguous_Muni_GEOID_List <- Ambiguous_Muni_Names[['GEOID']] # extract GEOIDs for tract matching
rm(Ambiguous_Muni_Names_Boolean, Ambiguous_Muni_Names)

# pull ambiguous cousub rows from PSH cousubs dataframe
place_PSH_good_Cousubs <- place_PSH_Cousubs_Already %>% filter(!name %in% Ambiguous_Muni_Name_List) # gets all the good ones; anything with a valid geoid and any township that's unambiguous
place_PSH_bad_Cousubs <- place_PSH_Cousubs_Already %>% filter(name %in% Ambiguous_Muni_Name_List) # only ambiguous townships go here
rm(place_PSH_Cousubs_Already)

# make a join field for good cousubs with the Census file
place_PSH_good_Cousubs$NAMELSAD <- str_to_upper(sub('...', '', place_PSH_good_Cousubs$name))

# MANUAL ADJUSTMENTS TO NAMES GO HERE!
if (cousub_year == '2023' & state_code == '34') {
  place_PSH_good_Cousubs$NAMELSAD[place_PSH_good_Cousubs$NAMELSAD == "PRINCETON BOROUGH"] <- "PRINCETON" # manually set Princeton Borough (Mercer County) to Princeton to match Census name since HUD has old one
}

# joining good cousubs to TIGER
Cousubs_Proj_no_geo <- st_drop_geometry(Cousubs_Proj) # drop geometry
Cousubs_Proj_no_geo$NAMELSAD <- str_to_upper(Cousubs_Proj_no_geo$NAMELSAD) # update format of join field
place_PSH_good_Cousubs_with_Munis <- left_join(place_PSH_good_Cousubs, Cousubs_Proj_no_geo, by = "NAMELSAD") # put them together

# for testing only
place_PSH_good_Cousubs_with_Munis_Duplicates <- duplicated(pull(place_PSH_good_Cousubs_with_Munis,NAMELSAD)) | duplicated(pull(place_PSH_good_Cousubs_with_Munis,NAMELSAD), fromLast=TRUE)
place_PSH_good_Cousubs_with_Munis_Duplicated <- place_PSH_good_Cousubs_with_Munis[place_PSH_good_Cousubs_with_Munis_Duplicates, c('COUNTYFP','NAMELSAD',"GEOID")]
rm(place_PSH_good_Cousubs_with_Munis_Duplicated, place_PSH_good_Cousubs)

# Handle the remainders
place_PSH_remainders$NAMELSAD <- str_to_upper(substr(place_PSH_remainders$name,17,nchar(place_PSH_remainders$name))) # trim to 
place_PSH_remainders$PSH_name <- paste("NJ", str_to_upper(substr(place_PSH_remainders$name,17,nchar(place_PSH_remainders$name)))) # trim to 

place_PSH_good_remainders <- place_PSH_remainders %>% filter(!PSH_name %in% Ambiguous_Muni_Name_List) # 
place_PSH_bad_remainders <- place_PSH_remainders %>% filter(PSH_name %in% Ambiguous_Muni_Name_List) 

place_PSH_good_remainders_with_Munis <- left_join(place_PSH_good_remainders, Cousubs_Proj_no_geo, by = "NAMELSAD") # put them together

rm(place_PSH_good_remainders, place_PSH_remainders)

# create a common GISJOIN field across the three (CDP had GEOID.1, not GEOID)
place_PSH_good_CDPs_with_Munis$GISJOIN <- place_PSH_good_CDPs_with_Munis$GEOID.1
place_PSH_good_Cousubs_with_Munis$GISJOIN <- place_PSH_good_Cousubs_with_Munis$GEOID
place_PSH_good_remainders_with_Munis$GISJOIN <- place_PSH_good_remainders_with_Munis$GEOID

place_PSH_Cousubs_So_Far <- dplyr::bind_rows(place_PSH_good_CDPs_with_Munis,place_PSH_good_Cousubs_with_Munis,place_PSH_good_remainders_with_Munis) # put everything that has a geoid together

# hopefully this comes up as a dataframe with 0 rows
bad_cousub_match <- place_PSH_good_Cousubs_with_Munis %>% filter(is.na(GISJOIN)) # test for any missing geoids
rm(place_PSH_good_CDPs_with_Munis,place_PSH_good_Cousubs_with_Munis,place_PSH_good_remainders_with_Munis) # get rid of intermediate files

Final_Tract_Aggregation_List <- unique(c(Ambiguous_Muni_GEOID_List,Ambiguous_CDP_Muni_GEOID_List)) # list of all munis in the state that need to be built from tract-level data
rm(Ambiguous_Muni_GEOID_List,Ambiguous_CDP_Muni_Name_List,Ambiguous_Muni_Name_List,place_PSH_good_Cousubs_with_Munis_Duplicates,Ambiguous_CDP_Muni_GEOID_List)
rm(bad_cousub_match)

##########################################
## 8 - Create Tract to Cousub Crosswalk ##
##########################################

Census_Tracts_2020 <- st_read(paste("Census_Geographies/2020_tracts/tl_2020_", state_code,"_tract20.shp", sep = "")) # bring in Census Place level geometries
Census_Tracts_2020_Clean <- subset(Census_Tracts_2020, select = -c(STATEFP20,NAMELSAD20,MTFCC20,FUNCSTAT20,ALAND20,AWATER20,INTPTLAT20,INTPTLON20,COUNTYFP20,TRACTCE20,NAME20)) # remove extraneous fields 

Tract_Cousubs_2020 <- subset(Cousubs_Proj, GEOID %in% Final_Tract_Aggregation_List) # subset to county subdivisions that we may need to build from tracts

# REPROJECT AND NEGATIVE BUFFER ON TRACTS
Census_Tracts_2020_Proj <- st_transform(Census_Tracts_2020_Clean, paste0("+proj=utm +zone=",utm_zone_simple," +ellps=GRS80 +datum=NAD83", sep="")) #reproject to correct UTM zone
Tracts_2020_Neg_Buffer <- Census_Tracts_2020_Proj %>% st_buffer(-150)  # create the negative 150 foot buffer
Tracts_2020_Neg_Buffer$sqkm <- as.numeric(st_area(Tracts_2020_Neg_Buffer)/1000000)

Tract_Cousub_Intersects <- st_intersection(Tracts_2020_Neg_Buffer, Tract_Cousubs_2020) # try this
Tract_Cousub_Intersects$area <- as.numeric(st_area(Tract_Cousub_Intersects)/1000000)
Tract_Cousub_Intersects$coverage <- Tract_Cousub_Intersects$area/Tract_Cousub_Intersects$sqkm
Tract_Cousub_Intersects <- Tract_Cousub_Intersects %>% filter(grepl('T1', CLASSFP)) # remove incorporated places since they're already captured elsewhere
Tract_Cousub_Intersects <- Tract_Cousub_Intersects %>% filter(coverage > 0.01) # if the overlap is less than one percent of land area, we don't care about it

Tract_Cousub_Intersects_Imperfectly <- subset(Tract_Cousub_Intersects, coverage < 0.99999999)

tract_PSH_2023$GEOID20 <- paste(substr(tract_PSH_2023$code,1,5),substr(tract_PSH_2023$code, 6,nchar(tract_PSH_2023$code)), sep ='') # need an 11-character GEOID for matching

Tract_Cousub_Intersects <- st_drop_geometry(Tract_Cousub_Intersects) # drop geometry

# join these tracts in ambiguous munis only, filter to just places with PSH data
tract_PSH_2023_with_Munis <- left_join(tract_PSH_2023, Tract_Cousub_Intersects, by = "GEOID20") # put them together
tract_PSH_2023_with_Munis_Aggregation_List <- tract_PSH_2023_with_Munis %>% filter(!is.na(GEOID)) # test for any missing geoids
tract_PSH_2023_with_Munis_Aggregation_Non_Zero <- tract_PSH_2023_with_Munis_Aggregation_List %>% filter(Pg1_total_units > 0) # only include rows with actual PSH data

tract_PSH_2023_with_Munis_Aggregation_Non_Zero['GEOID20']

tract_PSH_2023_with_Munis_Aggregation_Non_Zero_Duplicates <- duplicated(pull(tract_PSH_2023_with_Munis_Aggregation_Non_Zero,GEOID20)) | duplicated(pull(tract_PSH_2023_with_Munis_Aggregation_Non_Zero,GEOID20), fromLast=TRUE)
tract_PSH_2023_with_Munis_Aggregation_Non_Zero[tract_PSH_2023_with_Munis_Aggregation_Non_Zero_Duplicates, c('GEOID20',"GEOID","Pg1_total_units","coverage")]

# MANUAL ADJUSTMENTS TO TRACT CROSSWALKS GO HERE
if (cousub_year == '2023' & state_code == '34') {
  tract_PSH_2023_with_Munis_Aggregation_Non_Zero <- tract_PSH_2023_with_Munis_Aggregation_Non_Zero %>% filter(!(GEOID20 == "34011010500" & GEOID == "3401171160"))
}
rm(tract_PSH_2023_with_Munis_Aggregation_List,tract_PSH_2023_with_Munis)

# make one more GISJOIN field
tract_PSH_2023_with_Munis_Aggregation_Non_Zero$GISJOIN <- tract_PSH_2023_with_Munis_Aggregation_Non_Zero$GEOID

# coerce here to avoid a type issue in the bind rows below
tract_PSH_2023_with_Munis_Aggregation_Non_Zero$Quarter <- as.character(tract_PSH_2023_with_Munis_Aggregation_Non_Zero$Quarter)

place_PSH_Unmerged_Final <- dplyr::bind_rows(tract_PSH_2023_with_Munis_Aggregation_Non_Zero, place_PSH_Cousubs_So_Far) # put everything that has a geoid together

write.csv(place_PSH_Unmerged_Final,'place_PSH_Unmerged_Final_2023.csv')

```

```{r setup, include=FALSE}
###################################################
## 9 - Merge CDP/Remainders and Demographic Data ##
###################################################

place_PSH_noNAs <- place_PSH_Unmerged_Final %>% # this code drops all the demographic data that we don't have
  select(
    where(
      ~!all(is.na(.x))
    )
  )

place_PSH_noNAs <- place_PSH_Unmerged_Final 

# sum occupied units for the programs that have any reporting (not 6 or 7) to make formulas easier later
place_PSH_noNAs$pg1_occupied_units <- place_PSH_noNAs$Pg1_total_units * place_PSH_noNAs$Pg1_pct_occupied / 100
place_PSH_noNAs$pg2_occupied_units <- place_PSH_noNAs$Pg2_total_units * place_PSH_noNAs$Pg2_pct_occupied / 100
place_PSH_noNAs$pg3_occupied_units <- place_PSH_noNAs$Pg3_total_units * place_PSH_noNAs$Pg3_pct_occupied / 100
place_PSH_noNAs$pg4_occupied_units <- place_PSH_noNAs$Pg4_total_units * place_PSH_noNAs$Pg4_pct_occupied / 100
place_PSH_noNAs$pg5_occupied_units <- place_PSH_noNAs$Pg5_total_units * place_PSH_noNAs$Pg5_pct_occupied / 100
place_PSH_noNAs$pg8_occupied_units <- place_PSH_noNAs$Pg8_total_units * place_PSH_noNAs$Pg8_pct_occupied / 100
place_PSH_noNAs$pg9_occupied_units <- place_PSH_noNAs$Pg9_total_units * place_PSH_noNAs$Pg9_pct_occupied / 100

place_PSH_Final <- place_PSH_noNAs %>%
  dplyr::group_by(GISJOIN) %>%
  summarise(count = n(), 
            name = ifelse(is.na(NAMELSAD.1),
                  NAMELSAD, # use this field only if NAMELSAD.1 is NA (for tracts, remainders and cousubs)
                  NAMELSAD.1), # otherwise use this field (for CDPs)
            county = COUNTYFP,
        ## Program 1 - Summary of all HUD Programs (634 PLACE entries with units, 422 reporting demographics) ##
            total_units = sum(Pg1_total_units, na.rm=TRUE), 
            total_pct_occupied = (sum(pg1_occupied_units, na.rm=TRUE)/sum(Pg1_total_units, na.rm=TRUE)*100),
            total_occupied = sum(pg1_occupied_units, na.rm=TRUE),
            total_pct_reported = (sum(Pg1_number_reported, na.rm=TRUE)/sum(Pg1_total_units, na.rm=TRUE)*100),
            total_reported = sum(Pg1_number_reported, na.rm=TRUE),
        		total_months_since_report = (sum(Pg1_number_reported * Pg1_months_since_report, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_people_reporting = sum(Pg1_people_total, na.rm=TRUE),
            total_people_per_unit = (sum(Pg1_people_total, na.rm=TRUE)/sum(Pg1_number_reported, na.rm=TRUE)),
            # Rent and Income #
            total_rent_per_month = (sum(Pg1_rent_per_month * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_spending_per_month = (sum(Pg1_spending_per_month * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            # Household Income Variables #
            total_hh_income = (sum(Pg1_hh_income * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_person_income = (sum(Pg1_person_income * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_lt5k = (sum(Pg1_pct_lt5k * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_5k_lt10k = (sum(Pg1_pct_5k_lt10k * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_10k_lt15k = (sum(Pg1_pct_10k_lt15k * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_15k_lt20k = (sum(Pg1_pct_15k_lt20k * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_ge20k = (sum(Pg1_pct_ge20k * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            # Major Source of Income #
            total_pct_wage_major = (sum(Pg1_pct_wage_major * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_welfare_major = (sum(Pg1_pct_welfare_major * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_other_major = (sum(Pg1_pct_other_major * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_median = (sum(Pg1_pct_median * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_lt50_median = (sum(Pg1_pct_lt50_median * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_lt30_median = (sum(Pg1_pct_lt30_median * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            # Presence of Children #
            total_pct_2adults = (sum(Pg1_pct_2adults * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_1adult = (sum(Pg1_pct_1adult * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_female_head = (sum(Pg1_pct_female_head * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_female_head_child = (sum(Pg1_pct_female_head_child * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            # Head or Spouse or Co-Head Has a Disability #
            total_pct_disabled_lt62 = (sum(Pg1_pct_disabled_lt62 * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_disabled_ge62 = (sum(Pg1_pct_disabled_ge62 * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_disabled_all = (sum(Pg1_pct_disabled_all * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            # Age of Head/Spouse (Whoever is Older) #
            total_pct_lt24_head = (sum(Pg1_pct_lt24_head * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_age25_50 = (sum(Pg1_pct_age25_50 * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_age51_61 = (sum(Pg1_pct_age51_61 * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_age62plus = (sum(Pg1_pct_age62plus * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_age85plus = (sum(Pg1_pct_age85plus * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            # Race and Ethnicity #
            total_pct_minority = (sum(Pg1_pct_minority * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_black_nonhsp = (sum(Pg1_pct_black_nonhsp * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_native_american_nonhsp = (sum(Pg1_pct_native_american_nonhsp * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_asian_pacific_nonhsp = (sum(Pg1_pct_asian_pacific_nonhsp * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_white_nothsp = (sum(Pg1_pct_white_nothsp * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_black_hsp = (sum(Pg1_pct_black_hsp * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_wht_hsp = (sum(Pg1_pct_wht_hsp * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_oth_hsp = (sum(Pg1_pct_oth_hsp * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_hispanic = (sum(Pg1_pct_hispanic * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_multi = (sum(Pg1_pct_multi * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            # Social Conditions #
            total_months_waiting = (sum(Pg1_months_waiting * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_months_from_movein = (sum(Pg1_months_from_movein * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_utility_allow = (sum(Pg1_pct_utility_allow * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_lt5kave_util_allow = (sum(Pg1_ave_util_allow * Pg1_number_reported, na.rm=TRUE))/sum(Pg1_number_reported, na.rm=TRUE),
        ## Program 2 - Public Housing (72 PLACE entries with units, 65 reporting demographics) ##
            pg2_units = sum(Pg2_total_units, na.rm=TRUE), 
            pg2_pct_occupied = ((sum(pg2_occupied_units, na.rm=TRUE))/sum(Pg2_total_units, na.rm=TRUE)*100),
            pg2_occupied_units = sum(pg2_occupied_units, na.rm=TRUE),
            pg2_pct_reported = (sum(Pg2_number_reported, na.rm=TRUE)/sum(pg2_occupied_units, na.rm=TRUE)*100),
            pg2_reported_units = sum(Pg2_number_reported, na.rm=TRUE), 
            pg2_months_since_report = (sum(Pg2_number_reported * Pg2_months_since_report, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_people_reporting = sum(Pg2_people_total, na.rm=TRUE),
            pg2_people_per_unit = (sum(Pg2_people_total, na.rm=TRUE)/sum(Pg2_number_reported, na.rm=TRUE)),
            # Rent and Income #
            pg2_rent_per_month = (sum(Pg2_rent_per_month * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_spending_per_month = (sum(Pg2_spending_per_month * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Household Income Variables #
            pg2_hh_income = (sum(Pg2_hh_income * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_person_income = (sum(Pg2_person_income * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_5k_lt10k = (sum(Pg2_pct_5k_lt10k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_10k_lt15k = (sum(Pg2_pct_10k_lt15k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_15k_lt20k = (sum(Pg2_pct_15k_lt20k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_ge20k = (sum(Pg2_pct_ge20k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Major Source of Income #
            pg2_pct_wage_major = (sum(Pg2_pct_wage_major * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_welfare_major = (sum(Pg2_pct_welfare_major * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_other_major = (sum(Pg2_pct_other_major * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_median = (sum(Pg2_pct_median * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt50_median = (sum(Pg2_pct_lt50_median * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt30_median = (sum(Pg2_pct_lt30_median * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Presence of Children #
            pg2_pct_2adults = (sum(Pg2_pct_2adults * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_1adult = (sum(Pg2_pct_1adult * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_female_head = (sum(Pg2_pct_female_head * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_female_head_child = (sum(Pg2_pct_female_head_child * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Head or Spouse or Co-Head Has a Disability #
            pg2_pct_disabled_lt62 = (sum(Pg2_pct_disabled_lt62 * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_disabled_ge62 = (sum(Pg2_pct_disabled_ge62 * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_disabled_all = (sum(Pg2_pct_disabled_all * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Age of Head/Spouse (Whoever is Older) #
            pg2_pct_lt24_head = (sum(Pg2_pct_lt24_head * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_age25_50 = (sum(Pg2_pct_age25_50 * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_age51_61 = (sum(Pg2_pct_age51_61 * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_age62plus = (sum(Pg2_pct_age62plus * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_age85plus = (sum(Pg2_pct_age85plus * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Race and Ethnicity #
            pg2_pct_minority = (sum(Pg2_pct_minority * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_black_nonhsp = (sum(Pg2_pct_black_nonhsp * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_native_american_nonhsp = (sum(Pg2_pct_native_american_nonhsp * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_asian_pacific_nonhsp = (sum(Pg2_pct_asian_pacific_nonhsp * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_white_nothsp = (sum(Pg2_pct_white_nothsp * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_black_hsp = (sum(Pg2_pct_black_hsp * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_wht_hsp = (sum(Pg2_pct_wht_hsp * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_oth_hsp = (sum(Pg2_pct_oth_hsp * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_hispanic = (sum(Pg2_pct_hispanic * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_multi = (sum(Pg2_pct_multi * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Social Conditions #
            pg2_months_waiting = (sum(Pg2_months_waiting * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_months_from_movein = (sum(Pg2_months_from_movein * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_utility_allow = (sum(Pg2_pct_utility_allow * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5kave_util_allow = (sum(Pg2_ave_util_allow * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Number of Bedrooms #
            pg2_pct_bed1 = (sum(Pg2_pct_bed1 * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_bed2 = (sum(Pg2_pct_bed2 * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_bed3 = (sum(Pg2_pct_bed3 * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_overhoused = (sum(Pg2_pct_overhoused * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Surrounding Census Tract #
            pg2_tpoverty = (sum(Pg2_tpoverty * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_tminority = (sum(Pg2_tminority * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_tpct_ownsfd = (sum(Pg2_tpct_ownsfd * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
        ## Program 3 - Housing Choice Vouchers (627 PLACE entries with units, 368 reporting demographics) ##
            pg3_units = sum(Pg3_total_units, na.rm=TRUE), 
            pg3_pct_occupied = (sum(pg3_occupied_units, na.rm=TRUE))/sum(Pg3_total_units, na.rm=TRUE),
            pg3_occupied_units = sum(pg3_occupied_units, na.rm=TRUE),
            pg3_pct_reported = (sum(Pg3_number_reported, na.rm=TRUE)/sum(pg3_occupied_units, na.rm=TRUE)*100),
            pg3_reported_units = sum(Pg3_number_reported, na.rm=TRUE), 
            pg3_months_since_report = (sum(pg3_occupied_units * Pg3_months_since_report, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_people_reporting = sum(Pg3_people_total, na.rm=TRUE),
            pg3_people_per_unit = (sum(Pg3_people_total, na.rm=TRUE)/sum(pg3_occupied_units, na.rm=TRUE)),
			pg3_months_since_report = (sum(Pg3_number_reported * Pg3_months_since_report, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_people_reporting = sum(Pg3_people_total, na.rm=TRUE),
            pg3_people_per_unit = (sum(Pg3_people_total, na.rm=TRUE)/sum(Pg3_number_reported, na.rm=TRUE)),
            # Rent and Income #
            pg3_rent_per_month = (sum(Pg3_rent_per_month * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_spending_per_month = (sum(Pg3_spending_per_month * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            # Household Income Variables #
            pg3_hh_income = (sum(Pg3_hh_income * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_person_income = (sum(Pg3_person_income * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_lt5k = (sum(Pg3_pct_lt5k * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_5k_lt10k = (sum(Pg3_pct_5k_lt10k * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_10k_lt15k = (sum(Pg3_pct_10k_lt15k * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_15k_lt20k = (sum(Pg3_pct_15k_lt20k * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_ge20k = (sum(Pg3_pct_ge20k * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            # Major Source of Income #
            pg3_pct_wage_major = (sum(Pg3_pct_wage_major * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_welfare_major = (sum(Pg3_pct_welfare_major * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_other_major = (sum(Pg3_pct_other_major * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_median = (sum(Pg3_pct_median * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_lt50_median = (sum(Pg3_pct_lt50_median * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_lt30_median = (sum(Pg3_pct_lt30_median * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            # Presence of Children #
            pg3_pct_2adults = (sum(Pg3_pct_2adults * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_1adult = (sum(Pg3_pct_1adult * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_female_head = (sum(Pg3_pct_female_head * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_female_head_child = (sum(Pg3_pct_female_head_child * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            # Head or Spouse or Co-Head Has a Disability #
            pg3_pct_disabled_lt62 = (sum(Pg3_pct_disabled_lt62 * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_disabled_ge62 = (sum(Pg3_pct_disabled_ge62 * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_disabled_all = (sum(Pg3_pct_disabled_all * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            # Age of Head/Spouse (Whoever is Older) #
            pg3_pct_lt24_head = (sum(Pg3_pct_lt24_head * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_age25_50 = (sum(Pg3_pct_age25_50 * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_age51_61 = (sum(Pg3_pct_age51_61 * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_age62plus = (sum(Pg3_pct_age62plus * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_age85plus = (sum(Pg3_pct_age85plus * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            # Race and Ethnicity #
            pg3_pct_minority = (sum(Pg3_pct_minority * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_black_nonhsp = (sum(Pg3_pct_black_nonhsp * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_native_american_nonhsp = (sum(Pg3_pct_native_american_nonhsp * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_asian_pacific_nonhsp = (sum(Pg3_pct_asian_pacific_nonhsp * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_white_nothsp = (sum(Pg3_pct_white_nothsp * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_black_hsp = (sum(Pg3_pct_black_hsp * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_wht_hsp = (sum(Pg3_pct_wht_hsp * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_oth_hsp = (sum(Pg3_pct_oth_hsp * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_hispanic = (sum(Pg3_pct_hispanic * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_multi = (sum(Pg3_pct_multi * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            # Social Conditions #
            pg3_months_waiting = (sum(Pg3_months_waiting * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_months_from_movein = (sum(Pg3_months_from_movein * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_utility_allow = (sum(Pg3_pct_utility_allow * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
            pg3_pct_lt5kave_util_allow = (sum(Pg3_ave_util_allow * Pg3_number_reported, na.rm=TRUE))/sum(Pg3_number_reported, na.rm=TRUE),
        ## Program 4 - Moderate Rehabilitation (13 PLACE entries with units, 8 reporting demographics) ##
            pg4_units = sum(Pg4_total_units, na.rm=TRUE), 
            pg4_pct_occupied = (sum(pg4_occupied_units, na.rm=TRUE))/sum(Pg4_total_units, na.rm=TRUE),
            pg4_occupied_units = sum(pg4_occupied_units, na.rm=TRUE),
            pg4_pct_reported = (sum(Pg4_number_reported, na.rm=TRUE)/sum(pg4_occupied_units, na.rm=TRUE)*100),
            pg4_reported_units = sum(Pg4_number_reported, na.rm=TRUE), 
            pg4_months_since_report = (sum(pg4_occupied_units * Pg4_months_since_report, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_people_reporting = sum(Pg4_people_total, na.rm=TRUE),
            pg4_people_per_unit = (sum(Pg4_people_total, na.rm=TRUE)/sum(pg4_occupied_units, na.rm=TRUE)),
			pg4_months_since_report = (sum(Pg4_number_reported * Pg4_months_since_report, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_people_reporting = sum(Pg4_people_total, na.rm=TRUE),
            pg4_people_per_unit = (sum(Pg4_people_total, na.rm=TRUE)/sum(Pg4_number_reported, na.rm=TRUE)),
            # Rent and Income #
            pg4_rent_per_month = (sum(Pg4_rent_per_month * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_spending_per_month = (sum(Pg4_spending_per_month * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            # Household Income Variables #
            pg4_hh_income = (sum(Pg4_hh_income * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_person_income = (sum(Pg4_person_income * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_lt5k = (sum(Pg4_pct_lt5k * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_5k_lt10k = (sum(Pg4_pct_5k_lt10k * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_10k_lt15k = (sum(Pg4_pct_10k_lt15k * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_15k_lt20k = (sum(Pg4_pct_15k_lt20k * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_ge20k = (sum(Pg4_pct_ge20k * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            # Major Source of Income #
            pg4_pct_wage_major = (sum(Pg4_pct_wage_major * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_welfare_major = (sum(Pg4_pct_welfare_major * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_other_major = (sum(Pg4_pct_other_major * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_median = (sum(Pg4_pct_median * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_lt50_median = (sum(Pg4_pct_lt50_median * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_lt30_median = (sum(Pg4_pct_lt30_median * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            # Presence of Children #
            pg4_pct_2adults = (sum(Pg4_pct_2adults * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_1adult = (sum(Pg4_pct_1adult * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_female_head = (sum(Pg4_pct_female_head * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_female_head_child = (sum(Pg4_pct_female_head_child * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            # Head or Spouse or Co-Head Has a Disability #
            pg4_pct_disabled_lt62 = (sum(Pg4_pct_disabled_lt62 * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_disabled_ge62 = (sum(Pg4_pct_disabled_ge62 * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_disabled_all = (sum(Pg4_pct_disabled_all * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            # Age of Head/Spouse (Whoever is Older) #
            pg4_pct_lt24_head = (sum(Pg4_pct_lt24_head * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_age25_50 = (sum(Pg4_pct_age25_50 * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_age51_61 = (sum(Pg4_pct_age51_61 * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_age62plus = (sum(Pg4_pct_age62plus * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_age85plus = (sum(Pg4_pct_age85plus * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            # Race and Ethnicity #
            pg4_pct_minority = (sum(Pg4_pct_minority * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_black_nonhsp = (sum(Pg4_pct_black_nonhsp * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_native_american_nonhsp = (sum(Pg4_pct_native_american_nonhsp * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_asian_pacific_nonhsp = (sum(Pg4_pct_asian_pacific_nonhsp * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_white_nothsp = (sum(Pg4_pct_white_nothsp * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_black_hsp = (sum(Pg4_pct_black_hsp * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_wht_hsp = (sum(Pg4_pct_wht_hsp * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_oth_hsp = (sum(Pg4_pct_oth_hsp * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_hispanic = (sum(Pg4_pct_hispanic * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_multi = (sum(Pg4_pct_multi * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            # Social Conditions #
            pg4_months_waiting = (sum(Pg4_months_waiting * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_months_from_movein = (sum(Pg4_months_from_movein * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_utility_allow = (sum(Pg4_pct_utility_allow * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
            pg4_pct_lt5kave_util_allow = (sum(Pg4_ave_util_allow * Pg4_number_reported, na.rm=TRUE))/sum(Pg4_number_reported, na.rm=TRUE),
        ## Program 5 - Project Based Section 8 (224 PLACE entries with units, 155 reporting demographics) ##
            pg5_units = sum(Pg5_total_units, na.rm=TRUE), 
            pg5_pct_occupied = (sum(pg5_occupied_units, na.rm=TRUE))/sum(Pg5_total_units, na.rm=TRUE),
            pg5_occupied_units = sum(pg5_occupied_units, na.rm=TRUE),
            pg5_pct_reported = (sum(Pg5_number_reported, na.rm=TRUE)/sum(pg5_occupied_units, na.rm=TRUE)*100),
            pg5_reported_units = sum(Pg5_number_reported, na.rm=TRUE), 
            pg5_months_since_report = (sum(pg5_occupied_units * Pg5_months_since_report, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_people_reporting = sum(Pg5_people_total, na.rm=TRUE),
            pg5_people_per_unit = (sum(Pg5_people_total, na.rm=TRUE)/sum(pg5_occupied_units, na.rm=TRUE)),
			pg5_months_since_report = (sum(Pg5_number_reported * Pg5_months_since_report, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_people_reporting = sum(Pg5_people_total, na.rm=TRUE),
            pg5_people_per_unit = (sum(Pg5_people_total, na.rm=TRUE)/sum(Pg5_number_reported, na.rm=TRUE)),
            # Rent and Income #
            pg5_rent_per_month = (sum(Pg5_rent_per_month * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_spending_per_month = (sum(Pg5_spending_per_month * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            # Household Income Variables #
            pg5_hh_income = (sum(Pg5_hh_income * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_person_income = (sum(Pg5_person_income * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_lt5k = (sum(Pg5_pct_lt5k * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_5k_lt10k = (sum(Pg5_pct_5k_lt10k * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_10k_lt15k = (sum(Pg5_pct_10k_lt15k * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_15k_lt20k = (sum(Pg5_pct_15k_lt20k * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_ge20k = (sum(Pg5_pct_ge20k * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            # Major Source of Income #
            pg5_pct_wage_major = (sum(Pg5_pct_wage_major * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_welfare_major = (sum(Pg5_pct_welfare_major * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_other_major = (sum(Pg5_pct_other_major * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_median = (sum(Pg5_pct_median * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_lt50_median = (sum(Pg5_pct_lt50_median * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_lt30_median = (sum(Pg5_pct_lt30_median * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            # Presence of Children #
            pg5_pct_2adults = (sum(Pg5_pct_2adults * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_1adult = (sum(Pg5_pct_1adult * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_female_head = (sum(Pg5_pct_female_head * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_female_head_child = (sum(Pg5_pct_female_head_child * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            # Head or Spouse or Co-Head Has a Disability #
            pg5_pct_disabled_lt62 = (sum(Pg5_pct_disabled_lt62 * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_disabled_ge62 = (sum(Pg5_pct_disabled_ge62 * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_disabled_all = (sum(Pg5_pct_disabled_all * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            # Age of Head/Spouse (Whoever is Older) #
            pg5_pct_lt24_head = (sum(Pg5_pct_lt24_head * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_age25_50 = (sum(Pg5_pct_age25_50 * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_age51_61 = (sum(Pg5_pct_age51_61 * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_age62plus = (sum(Pg5_pct_age62plus * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_age85plus = (sum(Pg5_pct_age85plus * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            # Race and Ethnicity #
            pg5_pct_minority = (sum(Pg5_pct_minority * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_black_nonhsp = (sum(Pg5_pct_black_nonhsp * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_native_american_nonhsp = (sum(Pg5_pct_native_american_nonhsp * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_asian_pacific_nonhsp = (sum(Pg5_pct_asian_pacific_nonhsp * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_white_nothsp = (sum(Pg5_pct_white_nothsp * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_black_hsp = (sum(Pg5_pct_black_hsp * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_wht_hsp = (sum(Pg5_pct_wht_hsp * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_oth_hsp = (sum(Pg5_pct_oth_hsp * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_hispanic = (sum(Pg5_pct_hispanic * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_multi = (sum(Pg5_pct_multi * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            # Social Conditions #
            pg5_months_waiting = (sum(Pg5_months_waiting * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_months_from_movein = (sum(Pg5_months_from_movein * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_utility_allow = (sum(Pg5_pct_utility_allow * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
            pg5_pct_lt5kave_util_allow = (sum(Pg5_ave_util_allow * Pg5_number_reported, na.rm=TRUE))/sum(Pg5_number_reported, na.rm=TRUE),
			  ## Program 6 - RentSup/RAP (1 PLACE entry with units, 0 reporting demographics) ##
#            pg6_units = sum(Pg6_total_units, na.rm=TRUE), # nothing more to say since no reporting (all NAs)
        ## Program 7 - S236/BMIR (12 PLACE entries with units, 0 reporting demographics) ##
            pg7_units = sum(Pg7_total_units, na.rm=TRUE), # nothing more to say since no demographic reporting
            pg7_reported = sum(Pg7_number_reported, na.rm=TRUE), 
            pg7_pct_reported = (sum(Pg7_number_reported, na.rm=TRUE)/sum(Pg7_total_units, na.rm=TRUE)*100),
        ## Program 8 - 202/PRAC (60 PLACE entries with units, 50 reporting demographics) ##
            pg8_units = sum(Pg8_total_units, na.rm=TRUE), 
            pg8_pct_occupied = (sum(pg8_occupied_units, na.rm=TRUE))/sum(Pg8_total_units, na.rm=TRUE),
            pg8_occupied_units = sum(pg8_occupied_units, na.rm=TRUE),
            pg8_pct_reported = (sum(Pg8_number_reported, na.rm=TRUE)/sum(pg8_occupied_units, na.rm=TRUE)*100),
            pg8_reported_units = sum(Pg8_number_reported, na.rm=TRUE), 
            pg8_months_since_report = (sum(pg8_occupied_units * Pg8_months_since_report, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_people_reporting = sum(Pg8_people_total, na.rm=TRUE),
            pg8_people_per_unit = (sum(Pg8_people_total, na.rm=TRUE)/sum(pg8_occupied_units, na.rm=TRUE)),
			pg8_months_since_report = (sum(Pg8_number_reported * Pg8_months_since_report, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_people_reporting = sum(Pg8_people_total, na.rm=TRUE),
            pg8_people_per_unit = (sum(Pg8_people_total, na.rm=TRUE)/sum(Pg8_number_reported, na.rm=TRUE)),
            # Rent and Income #
            pg8_rent_per_month = (sum(Pg8_rent_per_month * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_spending_per_month = (sum(Pg8_spending_per_month * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            # Household Income Variables #
            pg8_hh_income = (sum(Pg8_hh_income * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_person_income = (sum(Pg8_person_income * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_lt5k = (sum(Pg8_pct_lt5k * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_5k_lt10k = (sum(Pg8_pct_5k_lt10k * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_10k_lt15k = (sum(Pg8_pct_10k_lt15k * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_15k_lt20k = (sum(Pg8_pct_15k_lt20k * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_ge20k = (sum(Pg8_pct_ge20k * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            # Major Source of Income #
            pg8_pct_wage_major = (sum(Pg8_pct_wage_major * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_welfare_major = (sum(Pg8_pct_welfare_major * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_other_major = (sum(Pg8_pct_other_major * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_median = (sum(Pg8_pct_median * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_lt50_median = (sum(Pg8_pct_lt50_median * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_lt30_median = (sum(Pg8_pct_lt30_median * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            # Presence of Children #
            pg8_pct_2adults = (sum(Pg8_pct_2adults * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_1adult = (sum(Pg8_pct_1adult * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_female_head = (sum(Pg8_pct_female_head * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_female_head_child = (sum(Pg8_pct_female_head_child * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            # Head or Spouse or Co-Head Has a Disability #
            pg8_pct_disabled_lt62 = (sum(Pg8_pct_disabled_lt62 * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_disabled_ge62 = (sum(Pg8_pct_disabled_ge62 * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_disabled_all = (sum(Pg8_pct_disabled_all * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            # Age of Head/Spouse (Whoever is Older) #
            pg8_pct_lt24_head = (sum(Pg8_pct_lt24_head * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_age25_50 = (sum(Pg8_pct_age25_50 * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_age51_61 = (sum(Pg8_pct_age51_61 * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_age62plus = (sum(Pg8_pct_age62plus * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_age85plus = (sum(Pg8_pct_age85plus * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            # Race and Ethnicity #
            pg8_pct_minority = (sum(Pg8_pct_minority * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_black_nonhsp = (sum(Pg8_pct_black_nonhsp * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_native_american_nonhsp = (sum(Pg8_pct_native_american_nonhsp * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_asian_pacific_nonhsp = (sum(Pg8_pct_asian_pacific_nonhsp * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_white_nothsp = (sum(Pg8_pct_white_nothsp * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_black_hsp = (sum(Pg8_pct_black_hsp * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_wht_hsp = (sum(Pg8_pct_wht_hsp * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_oth_hsp = (sum(Pg8_pct_oth_hsp * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_hispanic = (sum(Pg8_pct_hispanic * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_multi = (sum(Pg8_pct_multi * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            # Social Conditions #
            pg8_months_waiting = (sum(Pg8_months_waiting * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_months_from_movein = (sum(Pg8_months_from_movein * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_utility_allow = (sum(Pg8_pct_utility_allow * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),
            pg8_pct_lt5kave_util_allow = (sum(Pg8_ave_util_allow * Pg8_number_reported, na.rm=TRUE))/sum(Pg8_number_reported, na.rm=TRUE),        
			  ## Program 9 - 811/PRACs (120 PLACE entries with units, 24 reporting demographics) ##
                        pg9_units = sum(Pg9_total_units, na.rm=TRUE), 
            pg9_pct_occupied = (sum(pg9_occupied_units, na.rm=TRUE))/sum(Pg9_total_units, na.rm=TRUE),
            pg9_occupied_units = sum(pg9_occupied_units, na.rm=TRUE),
            pg9_pct_reported = (sum(Pg9_number_reported, na.rm=TRUE)/sum(pg9_occupied_units, na.rm=TRUE)*100),
            pg9_reported_units = sum(Pg9_number_reported, na.rm=TRUE), 
            pg9_months_since_report = (sum(pg9_occupied_units * Pg9_months_since_report, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_people_reporting = sum(Pg9_people_total, na.rm=TRUE),
            pg9_people_per_unit = (sum(Pg9_people_total, na.rm=TRUE)/sum(pg9_occupied_units, na.rm=TRUE)),
			pg9_months_since_report = (sum(Pg9_number_reported * Pg9_months_since_report, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_people_reporting = sum(Pg9_people_total, na.rm=TRUE),
            pg9_people_per_unit = (sum(Pg9_people_total, na.rm=TRUE)/sum(Pg9_number_reported, na.rm=TRUE)),
            # Rent and Income #
            pg9_rent_per_month = (sum(Pg9_rent_per_month * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_spending_per_month = (sum(Pg9_spending_per_month * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            # Household Income Variables #
            pg9_hh_income = (sum(Pg9_hh_income * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_person_income = (sum(Pg9_person_income * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_lt5k = (sum(Pg9_pct_lt5k * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_5k_lt10k = (sum(Pg9_pct_5k_lt10k * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_10k_lt15k = (sum(Pg9_pct_10k_lt15k * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_15k_lt20k = (sum(Pg9_pct_15k_lt20k * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_ge20k = (sum(Pg9_pct_ge20k * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            # Major Source of Income #
            pg9_pct_wage_major = (sum(Pg9_pct_wage_major * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_welfare_major = (sum(Pg9_pct_welfare_major * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_other_major = (sum(Pg9_pct_other_major * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_median = (sum(Pg9_pct_median * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_lt50_median = (sum(Pg9_pct_lt50_median * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_lt30_median = (sum(Pg9_pct_lt30_median * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            # Presence of Children #
            pg9_pct_2adults = (sum(Pg9_pct_2adults * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_1adult = (sum(Pg9_pct_1adult * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_female_head = (sum(Pg9_pct_female_head * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_female_head_child = (sum(Pg9_pct_female_head_child * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            # Head or Spouse or Co-Head Has a Disability #
            pg9_pct_disabled_lt62 = (sum(Pg9_pct_disabled_lt62 * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_disabled_ge62 = (sum(Pg9_pct_disabled_ge62 * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_disabled_all = (sum(Pg9_pct_disabled_all * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            # Age of Head/Spouse (Whoever is Older) #
            pg9_pct_lt24_head = (sum(Pg9_pct_lt24_head * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_age25_50 = (sum(Pg9_pct_age25_50 * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_age51_61 = (sum(Pg9_pct_age51_61 * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_age62plus = (sum(Pg9_pct_age62plus * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_age85plus = (sum(Pg9_pct_age85plus * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            # Race and Ethnicity #
            pg9_pct_minority = (sum(Pg9_pct_minority * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_black_nonhsp = (sum(Pg9_pct_black_nonhsp * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_native_american_nonhsp = (sum(Pg9_pct_native_american_nonhsp * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_asian_pacific_nonhsp = (sum(Pg9_pct_asian_pacific_nonhsp * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_white_nothsp = (sum(Pg9_pct_white_nothsp * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_black_hsp = (sum(Pg9_pct_black_hsp * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_wht_hsp = (sum(Pg9_pct_wht_hsp * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_oth_hsp = (sum(Pg9_pct_oth_hsp * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_hispanic = (sum(Pg9_pct_hispanic * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_multi = (sum(Pg9_pct_multi * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            # Social Conditions #
            pg9_months_waiting = (sum(Pg9_months_waiting * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_months_from_movein = (sum(Pg9_months_from_movein * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_utility_allow = (sum(Pg9_pct_utility_allow * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE),
            pg9_pct_lt5kave_util_allow = (sum(Pg9_ave_util_allow * Pg9_number_reported, na.rm=TRUE))/sum(Pg9_number_reported, na.rm=TRUE)) %>% distinct(GISJOIN, .keep_all = TRUE)

###################################
## 10 - Final Cleanup and Output ##
###################################

# Clean up town names (optional since we have GISJOIN but nice if you want to examine this document)
place_PSH_Final$name <- str_to_title(place_PSH_Final$name)

if (cousub_year == '2023' & state_code == '34') {
  place_PSH_Final$name[place_PSH_Final$GISJOIN == 3400102080] <- "Atlantic City" # 
  place_PSH_Final$name[place_PSH_Final$GISJOIN == 3400120350] <- "Egg Harbor City" # 
  place_PSH_Final$name[place_PSH_Final$GISJOIN == 3400143890] <- "Margate City" # 
  place_PSH_Final$name[place_PSH_Final$GISJOIN == 3400175620] <- "Ventnor City" # 
  place_PSH_Final$name[place_PSH_Final$GISJOIN == 3401736000] <- "Jersey City" # 
  place_PSH_Final$name[place_PSH_Final$GISJOIN == 3401774630] <- "Union City" # 
  place_PSH_Final$name[place_PSH_Final$GISJOIN == 3401313045] <- "City of Orange Township" # 
  place_PSH_Final$name[place_PSH_Final$GISJOIN == 3402502440] <- "Avon-by-the-Sea Borough" # 
}

# replace all the infinite and NaN values with NA to avoid causing trouble with mapping?

write.csv(place_PSH_Final,paste('place_2023_PSH_Final_',state_abbreviation,'.csv',sep=''), na = "")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
