---
title: "Tract to Cousub Conversion"
author: "Will P"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}

getwd()

library(sf) # use this to read geojsons and shapefiles
library(tmap) # use this to map them
library(dplyr) # use this to join and manipulate data frames
library(tidyverse)

place_PSH <- read.csv(file = 'NJ_PLACE_2020_WP.csv')

place_PSH <- subset(place_PSH, select = -c(gsl,states,sumlevel,sub_program,entities))

place_PSH[place_PSH==-1]<-0 # replace -1 with 0 throughout (missing data)
place_PSH[place_PSH==-4]<-NA # replace -4 with NA throughout (suppressed demographic data)
place_PSH[place_PSH==-5]<-NA # replace -5 with NA throughout (reporting under 50% demographic data)

# section of manual geoid updates for NJ townships with duplicate names in different counties
place_PSH$code[place_PSH$name == "NJ FRANKLIN TOWNSHIP"] <- 3424840 # manually set Franklin Township (Gloucester County)
place_PSH$code[place_PSH$name == "NJ GREENWICH TOWNSHIP"] <- 3428170 # manually set Greenwich Township (Cumberland County)
place_PSH$code[place_PSH$name == "NJ SPRINGFIELD TOWNSHIP"] <- 3470020 # manually set Springfield Township (Union County)
place_PSH$code[place_PSH$name == "NJ UNION TOWNSHIP"] <- 3474480 # manually set Union Township (Union County) 
place_PSH$code[place_PSH$name == "NJ WASHINGTON TOWNSHIP"] <- 3477135 # manually set Washington Township (Bergen County) 

place_PSH$code[place_PSH$name == "NJ REMAINDER OF FAIRFIELD TOWNSHIP"] <- 3422350 # manually set Remainder of Fairfield Township (Cumberland County)
place_PSH$code[place_PSH$name == "NJ REMAINDER OF GREENWICH TOWNSHIP"] <- 3428185 # manually set Remainder of Greenwich Township (Gloucester County)
place_PSH$code[place_PSH$name == "NJ REMAINDER OF MANSFIELD TOWNSHIP"] <- 3443320 # manually set Remainder of Mansfield Township (Warren County)

prefixes <- unique(place_PSH$program) # get all the unique program names used in the dataset

place_PSH <- pivot_wider( # pivot them to one row per cdp/cousub/remainder
  place_PSH,
  id_cols = NULL,
  names_from = program,
  names_prefix = "",
  names_sep = "_",
  names_glue = "Pg{program}_{.value}",
  values_from = c(program_label,total_units,pct_occupied,number_reported,pct_reported,months_since_report,months_since_report,pct_movein,people_per_unit,people_total,rent_per_month,spending_per_month,hh_income,person_income,pct_lt5k,pct_5k_lt10k,pct_10k_lt15k,pct_15k_lt20k,pct_ge20k,pct_wage_major,pct_welfare_major,pct_other_major,pct_median,pct_lt50_median,pct_lt30_median,pct_2adults,pct_1adult,pct_female_head,pct_female_head_child,pct_disabled_lt62,pct_disabled_ge62,pct_disabled_all,pct_lt24_head,pct_age25_50,pct_age51_61,pct_age62plus,pct_age85plus,pct_minority,pct_black_nonhsp,pct_native_american_nonhsp,pct_asian_pacific_nonhsp,pct_white_nothsp,pct_black_hsp,pct_wht_hsp,pct_oth_hsp,pct_hispanic,pct_multi,months_waiting,months_from_movein,pct_utility_allow,ave_util_allow,pct_bed1,pct_bed2,pct_bed3,pct_overhoused,tpoverty,tminority,tpct_ownsfd),
  names_sort = TRUE
)

# sort the dataframe so that each set of unit counts and demographic variables are together by program
names_to_order <- map(prefixes, ~ names(place_PSH)[grep(paste0(.x,"_"), names(place_PSH))]) %>% unlist
names_id <- setdiff(names(place_PSH), names_to_order)
place_PSH <- place_PSH %>%
  select(names_id, names_to_order)

rm(names_id, names_to_order,prefixes) # remove intermediate outputs

```

```{r cars}

place_PSH_CDPs <- place_PSH %>% filter(grepl('CDP', name)) # extract CDPs
place_PSH_no_CDPs <- place_PSH %>% filter(!grepl('CDP', name)) # filter them out of the main dataset
place_PSH_999999s <- filter(place_PSH_no_CDPs, code == '3499999') # extract cousubs without geoids, including remainders
place_PSH_geoID <- filter(place_PSH_no_CDPs, code != '3499999') # extract cousubs with geoids
place_PSH_remainders <- place_PSH_999999s %>% filter(grepl('REMAINDER', name)) # extract remainders of cousubs
place_PSH_othercousubs <- place_PSH_999999s %>% filter(!grepl('REMAINDER', name)) # extract other cousubs without geoids

place_PSH_Cousubs_Already <- rbind(place_PSH_geoID, place_PSH_othercousubs) # get things that are already aggregated to cousub

place_PSH_Cousubs_Already$Join_Name <- str_to_title(substr(place_PSH_Cousubs_Already$name,4,nchar(place_PSH_Cousubs_Already$name)))

rm(place_PSH_no_CDPs, place_PSH_geoID, place_PSH_othercousubs, place_PSH_999999s) # remove intermediate steps

# come up with a list of cousubs that need to be manually aggregated

manual_tract_aggregation_list <- c(3402970320,3402903050,3401304695,3401306260,3400129280,3402129310,3401133120,3402133180,3401139450,3402139510,3401547250,3402347280,3402554270,3402954300,3401577180,3402777240,3404177300,3401974420,3400569990)

# this is a new note

# these four because 
#Stafford (Ocean) 3402970320
#Barnegat (Ocean) 3402903050
#Belleville (Essex) 3401304695
#Bloomfield (Essex) 3401306260

#Union (Hunterdon) 3401974420 # these two have zero units but the same name as another one
#Springfield (Burlington) 3400569990

#Hamilton (Atlantic) 3400129280
#Hamilton (Mercer) 3402129310
#Hopewell (Cumberland) 3401133120
#Hopewell (Mercer) 3402133180
#Lawrence (Cumberland) 3401139450
#Lawrence (Mercer) 3402139510
#Monroe (Gloucester) 3401547250
#Monroe (Middlesex) 3402347280
#Ocean (Monmouth) 3402554270
#Ocean (Ocean) 3402954300
#Washington (Gloucester) 3401577180
#Washington (Morris) 3402777240
#Washington (Warren) 3404177300

```

```{r cars}

CDP_to_Cousub_Mapping <- read.csv('CDP_to_Cousub_Mapping.csv')

CDP_to_Cousub_Mapping$code <- as.character(CDP_to_Cousub_Mapping$GEOID10)
glimpse(CDP_to_Cousub_Mapping)

CDP_to_Cousub_Mapping <- filter(CDP_to_Cousub_Mapping, MUNI_MUN_LABEL != 'Byram Township') # remove one of the ambiguous CDPs since all housing units are in Sparta Township

place_PSH_CDPs_with_Munis <- left_join(place_PSH_CDPs, CDP_to_Cousub_Mapping, by = "code") # put them together

place_PSH_CDPs_Manual <- filter(place_PSH_CDPs_with_Munis, is.na(MUNI_MUN_LABEL))

place_PSH_CDPs_with_Munis <- filter(place_PSH_CDPs_with_Munis, !is.na(MUNI_MUN_LABEL))

place_PSH_CDPs_with_Munis$CENSUS2010 <- place_PSH_CDPs_with_Munis$MUNI_CENSUS2010 # need a common join field later

rm(place_PSH_CDPs, place_PSH_CDPs_Manual) # get rid of earlier issues

# We create a field called PSH_Join to disambiguate cousubs of the same name since we have place codes and names
NJ_Munis_for_Matching <- read.csv('NJ_Munis_for_Matching.csv') # bring in our cousub list to match with
NJ_Munis_for_Matching$place <- substr(NJ_Munis_for_Matching$GISJOIN,7,11) # get place code from GISJOIN
NJ_Munis_for_Matching$PSH_Join <- paste0(NJ_Munis_for_Matching$place," ",NJ_Munis_for_Matching$MUN_LABEL) # paste it to label

# Remove the "Missing" row
place_PSH_Cousubs_Missing <- filter(place_PSH_Cousubs_Already, code == '34XXXXX')
place_PSH_Cousubs_Not_Missing <- filter(place_PSH_Cousubs_Already, !code == '34XXXXX')

# Get the 99999s out
place_PSH_Cousubs_Already_99999s <- filter(place_PSH_Cousubs_Not_Missing, code == '3499999')
place_PSH_Cousubs_Already_Valid <- filter(place_PSH_Cousubs_Not_Missing, !code == '3499999')

place_PSH_Cousubs_Already_Valid$PSH_Join <- paste0(place_PSH_Cousubs_Already_Valid$place," ",place_PSH_Cousubs_Already_Valid$Join_Name)

place_PSH_Cousubs_Already_Matched <- left_join(place_PSH_Cousubs_Already_Valid, NJ_Munis_for_Matching, by = "PSH_Join") # put them together

place_PSH_Cousubs_Already_99999s_Matched <- left_join(place_PSH_Cousubs_Already_99999s, NJ_Munis_for_Matching, by = c("Join_Name" = "MUN_LABEL")) # put them together

place_PSH_Cousubs_Already$PSH_Join <- paste0(place_PSH_Cousubs_Already$place," ",place_PSH_Cousubs_Already$Join_Name) # 843 rows handled now, plus 416 for CDPs that aren't manual and 6 that are missing

rm(place_PSH_Cousubs_Not_Missing, place_PSH_Cousubs_Already_Valid) # clean up

place_PSH_Cousubs_So_Far <- dplyr::bind_rows(place_PSH_Cousubs_Already_99999s_Matched,place_PSH_Cousubs_Already_Matched,place_PSH_CDPs_with_Munis,place_PSH_Cousubs_Missing)

# 1265 rows handled so far (some still need to be combined at the muni level)
# 341 99999s (fix these by hand; 6 ambiguous townships that need to be sorted out and added to the input file to disambiguate)
# 8 Manual CDPs (assigning these is going to be its own manual work)
# 246 remainders (work to get these sorted and lined up with township)

```


```{r cars}

# Handle the remainders

place_PSH_remainders <- filter(place_PSH_remainders, !name == 'NJ REMAINDER OF WASHINGTON TOWNSHIP')

place_PSH_remainders$MUN_LABEL <- str_to_title(substr(place_PSH_remainders$name,17,nchar(place_PSH_remainders$name)))

place_PSH_remainders_matched <- left_join(place_PSH_remainders, NJ_Munis_for_Matching, by = "MUN_LABEL") # put them together

place_PSH_Cousubs_So_Far <- dplyr::bind_rows(place_PSH_Cousubs_So_Far,place_PSH_remainders_matched)

place_PSH_Unmerged_Final <- subset(place_PSH_Cousubs_So_Far, !CENSUS2010 %in% manual_tract_aggregation_list)
place_PSH_Unmerged_Manual <- subset(place_PSH_Cousubs_So_Far, CENSUS2010 %in% manual_tract_aggregation_list)


place_PSH_Unmerged_Final$CENSUS2010[place_PSH_Unmerged_Final$name == "NJ CITY OF ORANGE TOWNSHIP"] <- 3401313045 # manually set Remainder of Mansfield Township (Warren County)
place_PSH_Unmerged_Final$CENSUS2010[place_PSH_Unmerged_Final$name == "NJ PRINCETON TOWNSHIP"] <- 3402160915 # manually set Remainder of Mansfield Township (Warren County)

place_PSH_Unmerged_Final$CENSUS2010[place_PSH_Unmerged_Final$name == "NJ REMAINDER OF FAIRFIELD TOWNSHIP"] <- 3401122350 # manually set Remainder of Fairfield Township (Cumberland County)
place_PSH_Unmerged_Final$CENSUS2010[place_PSH_Unmerged_Final$name == "NJ REMAINDER OF GREENWICH TOWNSHIP"] <- 3401528185 # manually set Remainder of Greenwich Township (Gloucester County)
place_PSH_Unmerged_Final$CENSUS2010[place_PSH_Unmerged_Final$name == "NJ REMAINDER OF MANSFIELD TOWNSHIP"] <- 3404143320 # manually set Remainder of Mansfield Township (Warren County)

write.csv(place_PSH_Unmerged_Final,'place_PSH_Unmerged_Final.csv')

place_PSH_noNAs <- place_PSH_Unmerged_Final %>% # this code drops all the demographic data that we don't have
  select(
    where(
      ~!all(is.na(.x))
    )
  )

# sum occupied units for the programs that have any reporting (not 6 or 7) to make formulas easier later
place_PSH_noNAs$pg1_occupied_units <- place_PSH_noNAs$Pg1_total_units * place_PSH_noNAs$Pg1_pct_occupied / 100
place_PSH_noNAs$pg2_occupied_units <- place_PSH_noNAs$Pg2_total_units * place_PSH_noNAs$Pg2_pct_occupied / 100
place_PSH_noNAs$pg3_occupied_units <- place_PSH_noNAs$Pg3_total_units * place_PSH_noNAs$Pg3_pct_occupied / 100
place_PSH_noNAs$pg4_occupied_units <- place_PSH_noNAs$Pg4_total_units * place_PSH_noNAs$Pg4_pct_occupied / 100
place_PSH_noNAs$pg5_occupied_units <- place_PSH_noNAs$Pg5_total_units * place_PSH_noNAs$Pg5_pct_occupied / 100
place_PSH_noNAs$pg8_occupied_units <- place_PSH_noNAs$Pg8_total_units * place_PSH_noNAs$Pg8_pct_occupied / 100
place_PSH_noNAs$pg9_occupied_units <- place_PSH_noNAs$Pg9_total_units * place_PSH_noNAs$Pg9_pct_occupied / 100

place_PSH_Final <- place_PSH_noNAs %>%
  group_by(CENSUS2010) %>%
  summarise(count = n(), 
            name = ifelse(is.na(PSH_Join),
                  MUNI_MUN_LABEL,
                  substr(PSH_Join,7,nchar(PSH_Join))),
            county = str_to_title(COUNTY),
        ## Program 1 - Summary of all HUD Programs (634 PLACE entries with units, 422 reporting demographics) ##
            total_units = sum(Pg1_total_units, na.rm=TRUE), 
            total_occupied = sum(pg1_occupied_units, na.rm=TRUE),
            total_pct_occupied = (sum(pg1_occupied_units, na.rm=TRUE)/sum(Pg1_total_units, na.rm=TRUE)*100),
            total_reported = sum(Pg1_number_reported, na.rm=TRUE),
            total_pct_reported = (sum(Pg1_number_reported, na.rm=TRUE)/sum(Pg1_total_units, na.rm=TRUE)*100),
        ## Program 2 - Public Housing (72 PLACE entries with units, 65 reporting demographics) ##
            pg2_units = sum(Pg2_total_units, na.rm=TRUE), 
            pg2_pct_occupied = ((sum(pg2_occupied_units, na.rm=TRUE))/sum(Pg2_total_units, na.rm=TRUE)*100),
            pg2_occupied_units = sum(pg2_occupied_units, na.rm=TRUE),
            pg2_pct_reported = (sum(Pg2_number_reported, na.rm=TRUE)/sum(pg2_occupied_units, na.rm=TRUE)*100),
            pg2_reported_units = sum(Pg2_number_reported, na.rm=TRUE), 
            pg2_months_since_report = (sum(Pg2_number_reported * Pg2_months_since_report, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_people_total_reporting = sum(Pg2_people_total, na.rm=TRUE),
            pg2_people_per_unit = (sum(Pg2_people_total, na.rm=TRUE)/sum(Pg2_number_reported, na.rm=TRUE)),
            # Rent and Income #
            pg2_rent_per_month = (sum(Pg2_rent_per_month * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_spending_per_month = (sum(Pg2_spending_per_month * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Household Income Variables #
            pg2_hh_income = (sum(Pg2_hh_income * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_person_income = (sum(Pg2_person_income * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_5k_lt10k = (sum(Pg2_pct_5k_lt10k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_10k_lt15k = (sum(Pg2_pct_10k_lt15k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_15k_lt20k = (sum(Pg2_pct_15k_lt20k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_ge20k = (sum(Pg2_pct_ge20k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Major Source of Income #
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Presence of Children #
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Head or Spouse or Co-Head Has a Disability #
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Age of Head/Spouse (Whoever is Older) #
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Race and Ethnicity #
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Social Conditions #
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Number of Bedrooms #
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            # Surrounding Census Tract #
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),
            pg2_pct_lt5k = (sum(Pg2_pct_lt5k * Pg2_number_reported, na.rm=TRUE))/sum(Pg2_number_reported, na.rm=TRUE),

        ## Program 3 - Housing Choice Vouchers (627 PLACE entries with units, 368 reporting demographics) ##
            pg3_units = sum(Pg3_total_units, na.rm=TRUE), 
            pg3_reported = sum(Pg3_number_reported, na.rm=TRUE), 
            pg3_pct_reported = (sum(Pg3_number_reported, na.rm=TRUE)/sum(Pg3_total_units, na.rm=TRUE)*100),
            pg3_pct_occupied = (sum(Pg3_pct_occupied * Pg3_total_units, na.rm=TRUE))/sum(Pg3_total_units, na.rm=TRUE),
            pg3_occupied_units = (pg3_units * pg3_pct_occupied)/100,
            pg3_pct_reported = (sum(Pg3_number_reported, na.rm=TRUE)/sum(pg3_occupied_units, na.rm=TRUE)*100),
            pg3_months_since_report = sum((Pg3_total_units * Pg3_pct_occupied * Pg3_months_since_report), na.rm=TRUE)/sum((Pg3_total_units * Pg3_pct_occupied), na.rm=TRUE),
            pg3_people_total = sum(Pg3_people_total, na.rm=TRUE),
            pg3_people_per_unit = (sum(Pg3_people_total, na.rm=TRUE)/sum(pg3_occupied_units, na.rm=TRUE)),
        ## Program 4 - Moderate Rehabilitation (13 PLACE entries with units, 8 reporting demographics) ##
            pg4_units = sum(Pg4_total_units, na.rm=TRUE), 
            pg4_reported = sum(Pg4_number_reported, na.rm=TRUE), 
            pg4_pct_reported = (sum(Pg4_number_reported, na.rm=TRUE)/sum(Pg4_total_units, na.rm=TRUE)*100),
        ## Program 5 - Project Based Section 8 (224 PLACE entries with units, 155 reporting demographics) ##
            pg5_units = sum(Pg5_total_units, na.rm=TRUE), 
            pg5_reported = sum(Pg5_number_reported, na.rm=TRUE), 
            pg5_pct_reported = (sum(Pg5_number_reported, na.rm=TRUE)/sum(Pg5_total_units, na.rm=TRUE)*100),
        ## Program 6 - RentSup/RAP (1 PLACE entry with units, 0 reporting demographics) ##
            pg6_units = sum(Pg6_total_units, na.rm=TRUE), # nothing more to say since no reporting (all NAs)
        ## Program 7 - S236/BMIR (12 PLACE entries with units, 0 reporting demographics) ##
            pg7_units = sum(Pg7_total_units, na.rm=TRUE), # nothing more to say since no demographic reporting
            pg7_reported = sum(Pg7_number_reported, na.rm=TRUE), 
            pg7_pct_reported = (sum(Pg7_number_reported, na.rm=TRUE)/sum(Pg7_total_units, na.rm=TRUE)*100),
        ## Program 8 - 202/PRAC (60 PLACE entries with units, 50 reporting demographics) ##
            pg8_units = sum(Pg8_total_units, na.rm=TRUE), 
            pg8_reported = sum(Pg8_number_reported, na.rm=TRUE), 
            pg8_pct_reported = (sum(Pg8_number_reported, na.rm=TRUE)/sum(Pg8_total_units, na.rm=TRUE)*100),
        ## Program 9 - 811/PRACs (120 PLACE entries with units, 24 reporting demographics) ##
            pg9_units = sum(Pg9_total_units, na.rm=TRUE),
            pg9_reported = sum(Pg9_number_reported, na.rm=TRUE), 
            pg9_pct_reported = (sum(Pg9_number_reported, na.rm=TRUE)/sum(Pg9_total_units, na.rm=TRUE)*100))

place_PSH_Final <- filter(place_PSH_Final, !is.na(county)) %>% mutate_all(~ifelse(is.nan(.), NA, .)) # remove duplicate rows and NaN values

# replace all the infinite and NaN values with NA to avoid causing trouble with mapping?

write.csv(place_PSH_Final, 'place_PSH_Final.csv')

```
